server.port=3087
receipt.storage.path=src/main/resources/receipts/
spring.datasource.url=jdbc:postgresql://localhost:5432/RepairSystem
spring.datasource.username=RepairSystemUser
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
